spring:
  application:
    name: gateway
  session:
    store-type: redis
  data:
    redis:
      host: 10.116.64.14
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 22


server:
  port: 8000

logging:
  level:
    root: info

external:
  auth-api:
    uri: http://localhost:8083/api/auth
  account-api:
    uri: http://localhost:8081/api/accounts
  task-api:
    uri: http://localhost:8082/api/tasks
jwt:
  secret-key: "l7lD/bDeX1yqkdIWdecWa0QvHDLBA0LDAwwFKXYABJkvOSBRCv4Gotox6sATdG7pjoFV563J+CZ9lG54ktkPig=="